apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  secretName: argocd-cert
  privateKey:
    rotationPolicy: Always
  # commonName: Populated via patch
  dnsNames: [] # Populated via patch
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer