apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  gatewayClassName: cilium
  addresses: []
  listeners:
  - name: https-argocd
    protocol: HTTPS
    port: 443
    # hostname: Populated via patch
    tls:
      mode: Terminate
      certificateRefs:
      - name: argocd-cert
        kind: Secret