apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # email: Populate region via kustomize patch
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        route53:
          # region: Populate region via kustomize patch
          # role: Populate region via kustomize patch
          auth:
            kubernetes:
              serviceAccountRef:
                name: cert-manager-acme-dns01-route53
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # email: Populate region via kustomize patch
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          # region: Populate region via kustomize patch
          # role: Populate region via kustomize patch
          auth:
            kubernetes:
              serviceAccountRef:
                name: cert-manager-acme-dns01-route53
